name: Scrape Ebay

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  build:
    name: Scrape Ebay
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2
        with:
          version: "6.32.2"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Scrape Ebay
        run: pnpm run scrape-ebay
